export const MODAL_QUERY_PARAM = 'modal'

export const modalNames = {
	FORGOT_PASSWORD: 'forgot-password',
	WELCOME: 'welcome',
	RESEND_EMAIL: 'resend-email',
	EDIT_EMAIL: 'edit-email',
	EDIT_PASSWORD: 'edit-password',
	EDIT_PROFILE: 'edit-profile',
	EXIT_PROFILE: 'exit-profile',
	DELETE_PROFILE: 'delete-profile',
	USER_AVATARS: 'user-avatars',
	USER_POSTERS: 'user-posters',
	UPLOAD_AVATAR: 'upload-avatar',
	UPLOAD_POSTER: 'upload-poster',
	ADD_CAR: 'add-car',
	EDIT_CAR: 'edit-car',
	SET_CURRENT_CAR: 'set-current-car',
	UPLOAD_CAR_PHOTO: 'upload-car-photo',
	ADD_INSURANCE: 'add-insurance',
	EDIT_INSURANCE: 'edit-insurance',
	DELETE_INSURANCE: 'delete-insurance',
	UPLOAD_INSURANCE_PHOTO: 'upload-insurance-photo',
	CLEAR_INSURANCE_GALLERY: 'clear-insurance-gallery',
	BIND_INSURANCE_CONTACT: 'bind-insurance-contact',
	ADD_INSPECTION: 'add-inspection',
	EDIT_INSPECTION: 'edit-inspection',
	DELETE_INSPECTION: 'delete-inspection',
	UPLOAD_INSPECTION_PHOTO: 'upload-inspection-photo',
	CLEAR_INSPECTION_GALLERY: 'clear-inspection-gallery',
	ADD_CONTACT: 'add-contact',
	UPLOAD_CONTACT_PHOTO: 'upload-contact-photo',
	CLEAR_CONTACT_GALLERY: 'clear-contact-gallery',
	EDIT_CONTACT: 'edit-contact',
	DELETE_CONTACT: 'delete-contact',
} as const
