export const MODAL_QUERY_PARAM = 'modal'

export const modalNames = {
	FORGOT_PASSWORD: 'forgot-password',
	WELCOME: 'welcome',
	RESEND_EMAIL: 'resend-email',
	EDIT_EMAIL: 'edit-email',
	EDIT_PASSWORD: 'edit-password',
	EDIT_PROFILE: 'edit-profile',
	EXIT_PROFILE: 'exit-profile',
	DELETE_PROFILE: 'delete-profile',
	USER_AVATARS: 'user-avatars',
	USER_POSTERS: 'user-posters',
	UPLOAD_AVATAR: 'upload-avatar',
	UPLOAD_POSTER: 'upload-poster',
	ADD_CAR: 'add-car',
	EDIT_CAR: 'edit-car',
	UPLOAD_CAR_PHOTO: 'upload-car-photo',
	ADD_INSURANCE_POLICY: 'add-insurance-policy',
	EDIT_INSURANCE_POLICY: 'edit-insurance-policy',
	DELETE_INSURANCE_POLICY: 'delete-insurance-policy',
	UPLOAD_INSURANCE_PHOTO: 'upload-insurance-photo',
	CLEAR_INSURANCE_GALLERY: 'clear-insurance-gallery',
	SET_CURRENT_CAR: 'set-current-car',
} as const
