export const routes = {
	HOME: '/',
	AUTH: '/auth',
	RESET_PASSWORD: '/reset-password/:resetToken',
	ACTIVATION_SUCCESS: '/activation-success',
	PROFILE: '/profile',
	PRIVACY_POLICY: '/privacy-policy',
	TERMS_USE: '/terms-use',
	RECOVER_PASSWORD: '/recover-password',
	GARAGE: '/garage',
	PHONE_BOOK: 'phone-book',
	CONTACT_BY_ID: '/phone-book/:contactId',
	CAR_BY_ID: '/garage/:carId',
	INSURANCE_BY_ID: '/garage/:carId/insurance/:insuranceId?',
	INSPECTION_BY_ID: '/garage/:carId/inspection/:inspectionId?',
	SERVICE: '/service',
	FUEL: '/fuel',
	ACCESSORIES: '/accessories',
	GALLERY: '/gallery',
	STATISTICS: '/statistics',
	CONTACTS: '/support',
} as const
