export const routes = {
	HOME: '/',
	AUTH: '/auth',
	RESET_PASSWORD: '/reset-password/:resetToken',
	ACTIVATION_SUCCESS: '/activation-success',
	PROFILE: '/profile',
	PRIVACY_POLICY: '/privacy-policy',
	TERMS_USE: '/terms-use',
	RECOVER_PASSWORD: '/recover-password',
	GARAGE: '/garage',
	CAR_INFORMATION: '/garage/car',
	INSURANCE_POLICY: 'insurance',
	SERVICE: '/service',
	FUEL: '/fuel',
	ACCESSORIES: '/accessories',
	GALLERY: '/gallery',
	STATISTICS: '/statistics',
	CONTACTS: '/contacts',
}
