export const routes = {
	HOME: '/',
	AUTH: '/auth',
	PROFILE: '/profile',
	PRIVACY_POLICY: '/privacy-policy',
	TERMS_USE: '/terms-use',
	RECCOVER_PASSWORD: '/recover-password',
	GARAGE: '/garage',
	SERVICE: '/service',
	FUEL: '/fuel',
	ACCESSORIES: '/accessories',
	GALLERY: '/gallery',
	STATISTICS: '/statistics',
	CONTACTS: '/contacts',
}
